conditioning:
  method: ps
  params:
    scale: 0.3

data:
  name: imagenet
  root: ./data/val_images/

measurement:
  operator:
    name: gaussian_blur
    kernel_size: 61
    intensity: 3.0
  
  noise: 
    name: gaussian
    sigma: 0.05
