conditioning:
  method: ps
  params:
    scale: 0.5

data:
  name: imagenet
  root: ./data/val_images/

measurement:
  operator:
    name: inpainting
  mask_opt:
    mask_type: box
    mask_len_range: !!python/tuple [128, 129]  # for box
    # mask_prob_range: !!python/tuple [0.90, 0.92]  # for random
    image_size: 256


  noise:
    name: gaussian
    sigma: 0.05
