# This config file is for experiments on FFHQ dataset.
# For experiments on ImageNet dataset, please visit model_imagenet_config.yaml

# FFHQ: 
image_size: 256
num_channels: 128
num_res_blocks: 1
channel_mult: ""
learn_sigma: True
class_cond: False
use_checkpoint: False
attention_resolutions: 16
num_heads: 4
num_head_channels: 64
num_heads_upsample: -1
use_scale_shift_norm: True
dropout: 0.0
resblock_updown: True
use_fp16: False
use_new_attention_order: False

model_path: models/ffhq_10m.pt