conditioning:
  method: ps
  params:
    scale: 0.3

data:
  name: imagenet
  root: ./data/val_images/

measurement:
  operator:
    name: super_resolution
    in_shape: !!python/tuple [1, 3, 256, 256]
    scale_factor: 4
  
  noise: 
    name: gaussian
    sigma: 0.05
